### PR TITLE
Return value

### PR DESCRIPTION
**Pull request by y0urself**
**What**:

Saving the Return Value. If there was an Error in one File but not the last, a valid return value will be returned and not an erroneous value ...

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/python-gvm/blob/master/CHANGELOG.md) Entry
- [ ] Documentation

### CODE REVIEW

**Review by bjoernricks — CHANGES_REQUESTED** [review]
IMHO ret should be a value != 0 if one of the proc.returncode values is != 0. Currently it returns the value from the last call.

**Comment by y0urself** [comment]
> IMHO ret should be a value != 0 if one of the proc.returncode values is != 0. Currently it returns the value from the last call.

Yeah it is wrong since a while, right?
If Popen exits sucessfully it is returning 0 and negative integer otherwise ...

**Comment by bjoernricks** [comment]
> > IMHO ret should be a value != 0 if one of the proc.returncode values is != 0. Currently it returns the value from the last call.
> 
> ~Yeah it is wrong since a while, right?~
> ~If Popen exits sucessfully it is returning 0 and negative integer otherwise ...~
> 
> Edit: No it seems to be right?
> Look at the tests.
> The first test has no staged files, so it returns "ok" ...
> 
> The second tests returns an error() and it is !=0 ...
> ret stays 0 until any error appears und never gets 0 again ...

Sorry I can't find the test. Could you add a link to the test?

Before https://github.com/greenbone/autohooks-plugin-pylint/pull/19 it worked nicely because there was only one single return code. From looking at the code I am really sure that only the last return code is returned. If that is fine the whole linting is considered fine, the git hook doesn't fail and a commit is created.

**Comment by y0urself** [comment]
> > > IMHO ret should be a value != 0 if one of the proc.returncode values is != 0. Currently it returns the value from the last call.
> > 
> > 
> > ~Yeah it is wrong since a while, right?~
> > ~If Popen exits sucessfully it is returning 0 and negative integer otherwise ...~
> > Edit: No it seems to be right?
> > Look at the tests.
> > The first test has no staged files, so it returns "ok" ...
> > The second tests returns an error() and it is !=0 ...
> > ret stays 0 until any error appears und never gets 0 again ...
> 
> Sorry I can't find the test. Could you add a link to the test?
> 
> Before #19 it worked nicely because there was only one single return code. From looking at the code I am really sure that only the last return code is returned. If that is fine the whole linting is considered fine, the git hook doesn't fail and a commit is created.

https://github.com/greenbone/autohooks-plugin-pylint/blob/65d8e8494a8f7ff9c7cb9d23f3beddc2781f06b4/tests/test_pylint.py#L81

The value `ret` is set to 0 before the loop. 0 => everything is okay.
If the proc.returncode is != 0 it goes into the error case and ret is changed to the returncode. and it will never get 0 again, as I said before. 

> From looking at the code I am really sure that only the last return code is returned. If that is fine the whole linting is considered fine, the git hook doesn't fail and a commit is created.
THIS was the case before this PR and we did not see it. Now I changed it, this is why I PR'ed ...

**Comment by bjoernricks** [comment]
Ah I didn't notices the `if proc.returncode:` line. Thanks for clarification!

**Review by bjoernricks — APPROVED** [review]

**Comment by y0urself** [comment]
I got a little frustrated, trying to explain that ... 👍

**Pull request merged**
